### ISSUE TITLE
How to configure this app and enable 2FA

### ISSUE THREAD

**Issue by kimsyversen** [nextcloud/twofactor_sms#21]
Hi,  

I'm not sure how to use this app. I don't really need UI, but I need a way to force 2FA. With other 2FA-methods, users are able to disable 2FA and that is not a good thing in certain situations. SMS can also be questioned, but in my situation this is acceptable.

I have a theory that it would work to install this app and use the occ utility to add/configure users, and force 2FA. By doing that, even on first time login, users would need to use 2FA via SMS. Also, they cannot deactivate it.

Is anyone able to confirm this?

**Comment by ChristophWurst** [comment]
> but I need a way to force 2FA

This provider is active as soon as a phone number has been set. See https://github.com/nextcloud/twofactor_sms/blob/master/lib/Provider/SmsProvider.php#L150

> I have a theory that it would work to install this app and use the occ utility to add/configure users, and force 2FA. By doing that, even on first time login, users would need to use 2FA via SMS. Also, they cannot deactivate it.

Confirmed. But feel free to just try it out 😉

**Comment by ChristophWurst** [comment]
Depending on the gateway you want to use, you have to use one of the two available providers or implement your own. See https://github.com/nextcloud/twofactor_sms#supported-sms-services

**Comment by kimsyversen** [comment]
Thanks! I'll probably implement a norwegian Provider, then open a PR :)

**Comment by ChristophWurst** [comment]
> Thanks! I'll probably implement a norwegian Provider, then open a PR :)

Awesome! Looking forward to reviewing it! :-)
