### ISSUE TITLE
Nextcloud 13

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/twofactor_sms#25]
This app is not yet published for 13.

cc @ChristophWurst please update the info.xml

**Comment by ChristophWurst** [comment]
Will do. Note that this app is actually not really used by anyone. It's not even on the app store 😉

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/twofactor_sms/commit/eda767df550c20f9f1c6750311997beec2e4eb7a

**Comment by emresaracoglu** [comment]
> Note that this app is actually not really used by anyone

No. I am using your application & you are a really good engineer.

> It's not even on the app store 

Can I ask? Why not?

@ChristophWurst

**Comment by ChristophWurst** [comment]
> Can I ask? Why not?
> 
> @ChristophWurst

Simply because I already have got many apps to maintain and my time & resources are limited. If anybody would like to take over, they are more than welcome to do so!
