### ISSUE TITLE
App cannot be enabled because it makes the server unstable

### ISSUE THREAD

**Issue by corsaved** [nextcloud/twofactor_sms#8]
I update php up to 5.6, and copy twofactor_sms from GitHub in apps folder.
Next i try enabler app, but i see this messge for this app - "App cannot be enabled because it makes the server unstable"

After I checked a owncloud.log, and see this errors:

`Exception: {"Exception":"Exception","Message":"Could not load two-factor auth provider OCA\\TwoFactorSms\\Provider\\SmsProvider","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php(66): OC\\Authentication\\TwoFactorAuth\\Manager->getProviders(Object(OC\\User\\User))\n#1 \/var\/www\/html\/owncloud\/core\/Middleware\/TwoFactorMiddleware.php(93): OC\\Authentication\\TwoFactorAuth\\Manager->isTwoFactorAuthenticated(Object(OC\\User\\User))\n#2 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/Middleware\/MiddlewareDispatcher.php(93): OC\\Core\\Middleware\\TwoFactorMiddleware->beforeController(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#3 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(88): OC\\AppFramework\\Middleware\\MiddlewareDispatcher->beforeController(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#4 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/App.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#5 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/html\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#8 \/var\/www\/html\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/files')\n#9 \/var\/www\/html\/owncloud\/index.php(39): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php","Line":120}`

`include_once(): Failed opening '/var/www/html/owncloud/apps/twofactor_sms/appinfo/../vendor/autoload.php' for inclusion (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/pear:/usr/share/php:/var/www/html/owncloud') at /var/www/html/owncloud/apps/twofactor_sms/appinfo/app.php#21`

How i can fix this?

upd:
CentOS7, Apache, OwnCloud 9.1.1 (stable)

Thanks

**Comment by corsaved** [comment]
upd:
CentOS7, Apache, OwnCloud 9.1.1 (stable)

**Comment by pclemot** [comment]
Hi,

I encounter the same issue. The directory 'vendor' does not exists in the repository, dans is listed in the .gitignore file.

I'm running Nextcloud 11.0.0beta2 on Debian8, Nginx.

Many thanks.

**Comment by ChristophWurst** [comment]
> I encounter the same issue. The directory 'vendor' does not exists in the repository, dans is listed in the .gitignore file.

This directory is created by composer while installing dependencies. Run `composer.phar install` in the project's root directory to install the dependencies.
